MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("dt_voc_2007_trainval", "dt_voc_2012_trainval")
  TEST: ("clipart1k_test", )
SOLVER:
  MAX_ITER: 500
  BATCH_SIZE: 16
  BACKBONELR: 1e-5
  BOXHEADLR: 1e-5

OUTPUT_DIR: 'outputs/vgg_ssd300_voc0712_domian_transfer'